name: Full Recon & Takeover

on:
  push:
    branches: [master]

jobs:
  full-recon:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies & Tools
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y wget unzip jq git curl

          # Install Go tools
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest && sudo mv ~/go/bin/httpx /usr/bin/
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest && sudo mv ~/go/bin/subfinder /usr/bin/
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest && sudo mv ~/go/bin/dnsx /usr/bin/
          go install github.com/tomnomnom/qsreplace@latest && sudo mv ~/go/bin/qsreplace /usr/bin/
          go install github.com/lc/gau/v2/cmd/gau@latest && sudo mv ~/go/bin/gau /usr/bin/
          go install github.com/cybercdh/assetfinder@cybercdh && sudo mv ~/go/bin/assetfinder /usr/bin/
          go install github.com/PentestPad/subzy@latest && sudo mv ~/go/bin/subzy /usr/bin/

          # Install nuclei (latest release)
          LATEST_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r '.tag_name')
          CLEAN_VERSION=${LATEST_VERSION#v}
          wget https://github.com/projectdiscovery/nuclei/releases/download/${LATEST_VERSION}/nuclei_${CLEAN_VERSION}_linux_amd64.zip
          unzip -o nuclei_${CLEAN_VERSION}_linux_amd64.zip
          sudo mv nuclei /usr/bin/
          sudo chmod +x /usr/bin/nuclei
          rm -rf nuclei* *.md

      - name: Recon & Takeover Loop
        env:
          DOMAINS: ${{ secrets.DOMAIN }}
        run: |
          set -e
          mkdir -p results
          TODAY=$(date +%F)

          echo "$DOMAINS" | while read -r TARGET; do
            echo "🚀 Scanning: $TARGET"

            echo "[*] Subdomain Enumeration..."
            subfinder -d $TARGET -silent > sub1.txt
            assetfinder --subs-only $TARGET | grep "\.${TARGET}$" > sub2.txt
            cat sub1.txt sub2.txt | sort -u > results/${TARGET}-subdomains.txt
            rm -f sub1.txt sub2.txt

            echo "[*] Probing live hosts..."
            cat results/${TARGET}-subdomains.txt | httpx -silent -ports 80,443,8080,8443,3000,5000,8000,8888 \
              -title -td -tech-detect -web-server -ip -status-code -method \
              -probe -follow-redirects -random-agent -fr \
              -rate-limit 500 -timeout 10 -retries 3 -location \
              -o results/${TARGET}-live.txt

            echo "[*] Resolving DNS..."
            cat results/${TARGET}-live.txt | awk '{print $1}' | dnsx -silent -nc -a -cname -resp > results/${TARGET}-resolved.txt

            echo "[*] Running Subdomain Takeover Check with Subzy..."
            subzy run --targets results/${TARGET}-subdomains.txt \
              --concurrency 50 \
              --hide_fails \
              --timeout 10 \
              --vuln \
              --output results/subzy-takeover-${TARGET}.json

          awk '{print $1}' results/${TARGET}-resolved.txt | sort -u > results/${TARGET}-filtered.txt
          
          subzy run --targets results/${TARGET}-filtered.txt \
            --concurrency 50 \
            --hide_fails \
            --timeout 10 \
            --vuln \
            --output results/dnsx-takeover-${TARGET}.json

          done

      - name: Set Git Identity
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Commit & Push
        run: |
          git add results/
          git commit -m "🔎 Recon & Takeover Update $(date -u)" --no-verify || echo "No changes"
          git push origin master || true
